### PR TITLE
Add a timezone to the request

### PR DESCRIPTION
**Pull request by andyg0808**
Apparently Shopify cares now.

### CODE REVIEW

**Comment by andyg0808** [comment]
@djmetzle

**Comment by djmetzle** [comment]
CR :shipit:

**Comment by danielbeardsley** [comment]
Will this break again when we enter DST? And our diff is UTC-8hrs?

**Comment by djmetzle** [comment]
@danielbeardsley 
> Will this break again when we enter DST? And our diff is UTC-8hrs?

Potentially yes. But it will be less broken than before?

We didn't change the ECS task, so this is still running a full 24 hours worth of import each time. It's possible that on the Shopify side they start marking the `updated_at` field with dates marked `-8`. We didn't really explore the source for the shopify offset, or how the comparison is being done.

Either way, doing a full day back means a one hour delta isn't significant. But it's possible that our imported data will be an hour behind after the timezone change. I think that's better than 7 hours behind for now?

**Pull request merged**
