### PR TITLE
Shopify API: Use the latest supported version

### PR DESCRIPTION
**Pull request by evannoronha**
Summary
---
See https://github.com/iFixit/shopify-analytics/issues/5 for explaination.

QA
---
- Make sure the script does what we expect 
- Go read the readme and run through the development instructions.

Closes #https://github.com/ifixit/shopify-analytics/issues/5

### CODE REVIEW

**Review by djmetzle — APPROVED** [review]
CR :calendar:

**Comment by deltuh-vee** [comment]
dev_block ✊ 
I get this error when running the Docker image.
python_traceback

I think the `collections` package was changed? Might want to update `pymongo` or fix the python version.

**Comment by andyg0808** [comment]
It looks like the Shopify Python API package only got support for the latest API version in v9.0.0 (see [changelog](https://github.com/Shopify/shopify_python_api/blob/c6993e4414ee974d1bf16d2c1d61ff93f606f54a/CHANGELOG#L3-L6)). I think we might need to update the `requirements.txt` as well to update our API package version.

dev_block :+1: on that.

**Comment by evannoronha** [comment]
How do I test this in the context of airflow (with secrets)? I have some changes that fail on missing env variables.

image

**Comment by evannoronha** [comment]
I'm getting this to run up to the point where the script attempts to write to mongo, at which point I'm seeing some mongo error:

image

**Comment by evannoronha** [comment]
un_dev_block 🔥

**Review by sctice-ifixit — APPROVED** [review]
CR :flags:

**Comment by evannoronha** [comment]
QA 🔥 

image

**Comment by sctice-ifixit** [comment]
Nice work! And thanks for improving the docs for the next time around! :books: :heart:

**Comment by evannoronha** [comment]
QA 🔥  

image

**Comment by sctice-ifixit** [comment]
Oh! I was confused how we started seeing the failure with `collections.MutableMapping` when we hadn't changed anything but the API client we're using, but I just realized what's going on. We're just [depending on python3-alpine](https://github.com/iFixit/shopify-analytics/blob/master/Dockerfile#L1), and now [that resolves to python 3.10](https://github.com/docker-library/python/blob/db32c7803dfc67e5a359514371e66d6405695e45/3.10/alpine3.15/Dockerfile#L27), and in python 3.9, Python stopped allowing `collections.abc.X` to be imported as `collections.X`:

image

https://docs.python.org/3.10/whatsnew/changelog.html (search for `collections.abc`).

Anyways, all this to say that the last time we built this image `python3-alpine` probably resolved to a Python before 3.10, and building a new image broke code that depended on that. Since we've seen this happen once, I think we should probably specify a known-good minor version in the Dockerfile (3.10).

dev_block :hand: on that

**Comment by evannoronha** [comment]
> We're just depending on python3-alpine, and now that resolves to python 3.10, and in python 3.9, Python stopped allowing collections.abc.X to be imported as collections.X

I'm kind of split on this. I like that not version-clamping our image forces us to go in and update dependencies every so often. This seem preferable to the alternative of being months or even years behind latest release.

I think if we're going to version-clamp the dockerfile, we ought to set up Dependabot alerts as well, and I'd like to handle that in a separate PR.

**Comment by sctice-ifixit** [comment]
> I like that not version-clamping our image forces us to go in and update dependencies every so often. This seem preferable to the alternative of being months or even years behind latest release.

I don't think unintentionally breaking a build is worth the abstract benefit of being pushed to keep dependencies up to date, and as demonstrated by this pull, we're already being motivated to update dependencies by API changes. Security concerns here are quite limited (this isn't a service we're running), and the process either works for what we need or it doesn't. I.e., switching to a newer version of Python isn't likely to make the task work better on any axis that we care about; having Python upgrade to a new ~major~ minor version can basically only cause us problems, since "breaking changes" is implicit in a major version bump.

Independently, I'd be fine with setting up dependabot, although I think it's unlikely to do much for us besides create work.

__Edit__: I realized that I was referring to both major and minor version numbers, but I'm proposing clamping to a minor version. I don't think we _should_ need to do that, since semver.org says a minor version change shouldn't break backwards compatibility, but it looks like Python doesn't quite adhere to that, since this was definitely a break in backwards compatibility introduced in a new minor version.

**Comment by evannoronha** [comment]
Fair points. Version-clamp incoming.

**Comment by evannoronha** [comment]
image


un_dev_block 🔥 

QA 🔥

**Comment by sctice-ifixit** [comment]
CR :flags:

**Comment by evannoronha** [comment]
Played around with some GH Actions workflows then force-pushed my changes away. QA :carryover: CR :carryover:

**Comment by sctice-ifixit** [comment]
CR :flags:

**Comment by evannoronha** [comment]
QA :carryover: only touched the readme.

**Comment by evannoronha** [comment]
QA 🔥  ran through the readme and caught + fixed errors

**Review by sctice-ifixit — APPROVED** [review]
CR :flags:

**Review by djmetzle — APPROVED** [review]
CR :shipit:

**Review by andyg0808 — APPROVED** [review]

**Comment by andyg0808** [comment]
CR :goat: through e0a63a5

**Pull request merged**
