### PR TITLE
Drop `total_price_usd` field

### LINKED ISSUE #11: Fix task for upgraded Shopify API
This task is failing because the upstream Shopify API no longer exposes a `total_cost_usd` field:

https://github.com/iFixit/shopify-analytics/blob/6c6668d5628b89a1b21750d812a7d911ed8eee3f/get_orders.py#L36

Slack ref: https://ifixit.slack.com/archives/CNJ1K797G/p1692113075312969

### PR DESCRIPTION
**Pull request by djmetzle**
Fix up the `shopify-analytics` task to get it running again.

Closes: https://github.com/iFixit/shopify-analytics/issues/11

CC @iFixit/bi

### CODE REVIEW

**Comment by djmetzle** [comment]
This builds on cominor now.

**Comment by djmetzle** [comment]
Note: We'll need to build and push this task image manually, there's no automation.

Here are the DAGs:
- https://github.com/iFixit/airflow-dags/blob/master/shopify-analytics/au.py
- https://github.com/iFixit/airflow-dags/blob/master/shopify-analytics/ca.py

**Comment by djmetzle** [comment]
I'll try to scrape the password out of S3 and give these a test run on cominor.

**Comment by sterlinghirsh** [comment]
Since we're updating the api version, can we just go straight to 2023-07? Otherwise we're probably just going to have to do this again shortly.

**Comment by djmetzle** [comment]
@sterlinghirsh i'd rather not fold that into getting this back up and working.

But the groundwork for that has been set, updating the SDK to allow access to the new version.

**Comment by djmetzle** [comment]
```
 DEV  [djmetzle@cominor shopify-analytics ] (drop-total-price-usd-field) $ docker run --net=host -t --rm --env-file secrets.env --name shopify-analytics-dev shopify-analytics:development
Fetching orders since 2023-08-15T13:38:15.896982-07:00
Processing order 4970741956805 updated at: 2023-08-16 13:28:26-07:00
Processing order 4970698145989 updated at: 2023-08-16 13:13:43-07:00
Processing order 4970665312453 updated at: 2023-08-16 12:37:10-07:00
Processing order 4970647617733 updated at: 2023-08-16 12:17:04-07:00
Processing order 4970624450757 updated at: 2023-08-16 11:54:00-07:00
Processing order 4970610229445 updated at: 2023-08-16 11:39:03-07:00
Processing order 4970610032837 updated at: 2023-08-16 11:38:43-07:00
Processing order 4970587226309 updated at: 2023-08-16 11:14:44-07:00
Processing order 4970569400517 updated at: 2023-08-16 10:55:39-07:00
< ... >
```

Runs locally now. QA :shipit:

**Comment by djmetzle** [comment]
Carryover QA :+1:

**Comment by djmetzle** [comment]
Unless there is something else going on that i'm not tracking, it looks like the R app does not use this field:
https://github.com/iFixit/Stats/blob/master/ifixitR/R/shopifyUtils.R

**Comment by djmetzle** [comment]
An Org wide search looks promising. Though it does turn up that we are including this (now missing) field in a lot of test data on `ifixit/ifixit`.

**Comment by sterlinghirsh** [comment]
Let's just drop it. I think you're right it's probably not used (or not used much) so we can just deal with any fallout afterward. The field is gone from the data source so it's not like we have a choice at this point. Besides, neither of the two stores (CA/AU) are using USD anyway.

**Comment by djmetzle** [comment]
Sounds like a plan.

**Comment by sterlinghirsh** [comment]
CR :zap:

**Pull request merged**
